version: '3.8'

services:

  api:
    build: ../api
    ports:
      - "8080:8080"
    environment:
      - API_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - CORS_ALLOWED_ORIGINS=http://localhost:4200,http://localhost:3000,http://127.0.0.1:3000
      # Configurações do banco de dados - PostgreSQL LOCAL
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=creditos_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      # Configurações específicas da aplicação
      - APP_ENVIRONMENT=development
      - TEST_FEATURES_ENABLED=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - creditos-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    build: 
      context: ../web
      args:
        - ENVIRONMENT=development
    ports:
      - "3000:80"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - creditos-network

networks:
  creditos-network:
    driver: bridge
