version: '3.8'

services:

  api:
    build: ../api
    ports:
      - "8080:8080"
    environment:
      - API_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      - CORS_ALLOWED_ORIGINS=https://creditos.com.br,https://www.creditos.com.br
      # Configurações do banco de dados - PostgreSQL PRODUÇÃO
      - DB_HOST=postgres-prod
      - DB_PORT=5432
      - DB_NAME=creditos_prod
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      # Configurações específicas da aplicação
      - APP_ENVIRONMENT=production
      - TEST_FEATURES_ENABLED=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - creditos-network

  web:
    build: 
      context: ../web
      args:
        - ENVIRONMENT=production
    ports:
      - "3000:80"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - creditos-network

networks:
  creditos-network:
    driver: bridge
