version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper-prod
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - creditos-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka-prod
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    networks:
      - creditos-network

  api:
    build: ../api
    ports:
      - "8080:8080"
    environment:
      - API_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      - CORS_ALLOWED_ORIGINS=https://creditos.com.br,https://www.creditos.com.br
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_AUDIT_TOPIC=creditos-audit-events-prod
      # Configurações do banco de dados - PostgreSQL PRODUÇÃO
      - DB_HOST=postgres-prod
      - DB_PORT=5432
      - DB_NAME=creditos_prod
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      # Configurações específicas da aplicação
      - APP_ENVIRONMENT=production
      - TEST_FEATURES_ENABLED=false
    depends_on:
      kafka:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - creditos-network

  web:
    build: 
      context: ../web
      args:
        - ENVIRONMENT=production
    ports:
      - "3000:80"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - creditos-network

networks:
  creditos-network:
    driver: bridge
