# Configuração base - será sobrescrita pelos profiles específicos
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: creditos-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Configurações comuns a todos os ambientes
server:
  port: ${API_PORT:8080}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://127.0.0.1:4200}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    br.com.guilhermedealmeidafreitas.creditos: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true


# Configurações da aplicação
app:
  environment: ${APP_ENVIRONMENT:development}
  test-features:
    enabled: ${TEST_FEATURES_ENABLED:true}
  
  # Configurações de validação
  validation:
    pagination:
      default-page-size: 10
      max-page-size: 100
      min-page-size: 1
      default-page: 0
    
    string-validation:
      default-min-length: 1
      default-max-length: 255
      trim-enabled: true
      allow-empty: false
    
    number-validation:
      allow-negative: false
      allow-zero: true
      default-precision: 2
      max-precision: 10
    
    sort-fields:
      valid-sort-fields:
        - id
        - numeroCredito
        - numeroNfse
        - dataConstituicao
        - valorIssqn
        - tipoCredito
        - simplesNacional
        - aliquota
        - valorFaturado
        - valorDeducao
        - baseCalculo
      default-sort-field: id
      default-sort-direction: ASC