server:
  port: ${API_PORT:8080}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://hml.creditos.com.br,https://hml-creditos.com.br}

spring:
  application:
    name: creditos-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-hml}:${DB_PORT:5432}/${DB_NAME:creditos_hml}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:${DB_PASSWORD}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    br.com.guilhermedealmeidafreitas.creditos: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: false

# Configurações do Kafka
kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-hml:9092}
  topic:
    audit-events: ${KAFKA_AUDIT_TOPIC:creditos-audit-events-hml}
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    acks: all
    retries: 3
    batch-size: 16384
    linger-ms: 5
    buffer-memory: 33554432

# Configurações específicas de homologação
app:
  environment: homologation
  test-features:
    enabled: false
