server:
  port: ${API_PORT:8080}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://creditos.com.br,https://www.creditos.com.br}

spring:
  application:
    name: creditos-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-prod}:${DB_PORT:5432}/${DB_NAME:creditos_prod}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:${DB_PASSWORD}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    br.com.guilhermedealmeidafreitas.creditos: WARN
    org.springframework.web: ERROR
    org.hibernate.SQL: ERROR
    root: WARN

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false


# Configurações específicas de produção
app:
  environment: production
  test-features:
    enabled: false
