-- Script para criação da tabela credito
-- Execute este script conectado ao banco creditos_db

-- Criar a tabela credito
CREATE TABLE credito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_credito VARCHAR(50) NOT NULL,
    numero_nfse VARCHAR(50) NOT NULL,
    data_constituicao DATE NOT NULL,
    valor_issqn DECIMAL(15, 2) NOT NULL,
    tipo_credito VARCHAR(50) NOT NULL,
    simples_nacional BOOLEAN NOT NULL,
    aliquota DECIMAL(5, 2) NOT NULL,
    valor_faturado DECIMAL(15, 2) NOT NULL,
    valor_deducao DECIMAL(15, 2) NOT NULL,
    base_calculo DECIMAL(15, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Comentários das colunas
COMMENT ON TABLE credito IS 'Tabela para armazenar informações de créditos';
COMMENT ON COLUMN credito.id IS 'Identificador único do crédito';
COMMENT ON COLUMN credito.numero_credito IS 'Número do crédito';
COMMENT ON COLUMN credito.numero_nfse IS 'Número da NFSe';
COMMENT ON COLUMN credito.data_constituicao IS 'Data de constituição do crédito';
COMMENT ON COLUMN credito.valor_issqn IS 'Valor do ISSQN';
COMMENT ON COLUMN credito.tipo_credito IS 'Tipo do crédito (ISSQN, Outros, etc.)';
COMMENT ON COLUMN credito.simples_nacional IS 'Indica se é do Simples Nacional';
COMMENT ON COLUMN credito.aliquota IS 'Alíquota aplicada';
COMMENT ON COLUMN credito.valor_faturado IS 'Valor faturado';
COMMENT ON COLUMN credito.valor_deducao IS 'Valor da dedução';
COMMENT ON COLUMN credito.base_calculo IS 'Base de cálculo';

-- Criar índices para melhor performance
CREATE INDEX idx_credito_numero_credito ON credito(numero_credito);
CREATE INDEX idx_credito_numero_nfse ON credito(numero_nfse);
CREATE INDEX idx_credito_data_constituicao ON credito(data_constituicao);
CREATE INDEX idx_credito_tipo_credito ON credito(tipo_credito);

-- Função para atualizar o campo updated_at automaticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger para atualizar updated_at automaticamente
CREATE TRIGGER update_credito_updated_at 
    BEFORE UPDATE ON credito 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

